### ISSUE TITLE
<div/> elements in tabs are not visible

### ISSUE THREAD

**Issue by AndreasAmMueller** [ygoe/Frontfire#1]
When defining tab pages and placing other `<div/>` elements inside the tabs, these elements are not shown.

Example:    
```
<div class="tabs">
	<div title="Tab 1">
		<h1>This is Tab 1</h1>
		<div style="background: red;">
			// some content
		</div>
	</div>
	<div title="Tab 2">
		<h1>This is Tab 2</h1>
		<p>
			// some content
		</p>
	</div>
</div>
```

Result:    
On "Tab 1" only the heading is visible. "Tab 2" as expected.

Wanted:    
On "Tab 1" heading and red content should be visible.

Fix:    
Add `> ` at the beginning of this line to match only direct child `<div/>` elements.

https://github.com/ygoe/Frontfire/blob/32d7df4ecba826c8a5a32031a961f8ffb04935e9/src/css/modules/_tabs.scss#L64

**Comment by ygoe** [comment]
Thank you for the report. It should be working now.
